#
# Pre-commit hooks
#
minimum_pre_commit_version: "2.20.0"
default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg

repos:
  # Commitizen for commit message standardization
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.10.0
    hooks:
    - id: commitizen
      stages: [commit-msg]

  - repo: local
    hooks:
    - id: reuse-annotate
      name: REUSE Annotate
      entry: reuse
      args: [annotate, -c, "All contributors", -l, "GPL-2.0-or-later", --merge-copyrights ]
      language: python
      pass_filenames: true
      types_or: ["rust"]
