[package]
name = "algorithm"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace =true }
module_core = { workspace =true }
tokio.workspace = true
tracing.workspace = true

chrono = { version = "~0.4" }
async-trait = "~0.1"
