[package]
name = "laptimer"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace =true }
module_core = { workspace =true }
algorithm = { workspace =true }
tracing = { workspace =true }
tokio.workspace = true

chrono = { version = "~0.4" }
async-trait = "~0.1"
